blank_lines_upper_bound = 3
brace_style = "PreferSameLine"
format_strings = true
merge_imports = true
reorder_impl_items = true
report_fixme = "Unnumbered"
# TODO: uncomment :) report_todo = "Always"
struct_field_align_threshold = 5
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
indent_style = "Visual"